name: CI - Validate PR

# Trigger the workflow on pull requests to the main branch
on:
  pull_request:
    branches: [ main ]  # Replace 'main' with your default branch if different

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]  # Specify the Python version you want to support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo xargs -a packages.txt apt-get install -y
      shell: bash

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'  # Ensure 64-bit architecture

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Validate dependencies with pip-check
      run: |
        pip install pip-check
        pip-check
      continue-on-error: false  # Fail the workflow if dependencies are invalid

    - name: Test Streamlit App
      run: |
        pip install streamlit
        streamlit run app.py --server.headless true --browser.gatherUsageStats false &
        sleep 10  # Wait for the app to start
        curl --retry 5 --retry-delay 5 http://localhost:8501
      env:
        STREAMLIT_SERVER_HEADLESS: true
