name: CI - Validate PR

# Trigger the workflow on pull requests to the main branch
on:
  pull_request:
    branches: [ main ]  # Replace 'main' with your default branch if different

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Specify Python versions you support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Validate dependencies with pip-check
      run: |
        pip install pip-check
        pip-check --verbose
      continue-on-error: false  # Fail the workflow if dependencies are invalid

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 workflow-test/ app.py  # Adjust paths as necessary
      continue-on-error: false

    - name: Run Tests with pytest
      run: |
        pip install pytest
        pytest  # Ensure you have test files (e.g., tests/) in your repository
      continue-on-error: false

    - name: Test Streamlit App
      run: |
        pip install streamlit
        streamlit run workflow-test/app.py --server.headless true --browser.gatherUsageStats false &
        sleep 10  # Wait for the app to start
        # Optionally, you can add commands to perform HTTP requests to the app to ensure it's running
        # For example, using curl to check if the app is responding
        curl --retry 5 --retry-delay 5 http://localhost:8501
      env:
        STREAMLIT_SERVER_HEADLESS: true
